In [3]:
# check version of numpy
import numpy as np
print(np.__version__)

1.26.4


In [5]:
# array 
# the process of converting other data type array 
# that time we have to use array function 
# inbuilt function - comes under of numpy
a = [1,2,3,4,5]

In [9]:
print(type(a)) # <class 'list'>

<class 'list'>


In [25]:
# array()
a = np.array([1,2,3,4,5,6]) 

In [31]:
type(a) # numpy.ndarray

numpy.ndarray

In [35]:
print(a) # [1 2 3 4 5 6]

[1 2 3 4 5 6]


In [39]:
y = (12,23,53,13,45)
z = np.array(y)
print(z)
# Output:-
# [12 23 53 13 45]

[12 23 53 13 45]


In [41]:
# with complex number
w = [1,2,3,1+4j]
convert = np.array(w)
print(convert)
# converted all the numbers to complex
# [1.+0.j 2.+0.j 3.+0.j 1.+4.j]

[1.+0.j 2.+0.j 3.+0.j 1.+4.j]


In [43]:
# with float number
w = [1,2,3,1.0]
convert = np.array(w)
print(convert)
# [1. 2. 3. 1.]

[1. 2. 3. 1.]


In [53]:
x = 100
s=np.array(x)
print(type(s)) # <class 'numpy.ndarray'>

<class 'numpy.ndarray'>


In [69]:
blank_array = np.array([])
blank_array = np.array(())

In [71]:
blank_array

array([], dtype=float64)

In [83]:
# check dimnension
# ndim
print(convert.ndim)

1


In [85]:
# 2-d array in the form of matrix 
w1 = np.array([[1,2,3] , [4,5,6]])
print(w1)
# output
# [[1 2 3]
# [4 5 6]]

[[1 2 3]
 [4 5 6]]


In [97]:
print(w1.shape) # (2, 3)
print(w1.size) # 6
print(w1.dtype) # int32
print(w1.ndim) # 2

(2, 3)
6
int32
2


In [113]:
# i want to change the strucutre the matrix
# concept name : reshape
print(w1.reshape(3,2))
print()
print(w1.reshape(6,1))
print()
print(w1.reshape(1,6))
print()
print(w1.reshape(6))

# output:-
# [[1 2]
# [3 4]
# [5 6]]

[[1 2]
 [3 4]
 [5 6]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

[[1 2 3 4 5 6]]

[1 2 3 4 5 6]


In [121]:
new_array = np.array([[1,2,3] , [3,4,5] , [6,7,8]])
print(new_array.shape) # (3,3)
print(new_array.reshape(9))
print(new_array.reshape(1,9))

(3, 3)
[1 2 3 3 4 5 6 7 8]
[[1 2 3 3 4 5 6 7 8]]


In [123]:
print(new_array.reshape(-1)) # multi dimension array to single dimension array simply use -1 with reshape 

[1 2 3 3 4 5 6 7 8]


In [129]:
# flatten()
# convert 2-d aray to 1-d array 
print(new_array.flatten())

[1 2 3 3 4 5 6 7 8]


In [144]:
# parameter order
print(new_array.flatten(order = "C")) # C -> rows (by deafult execute thorugh order format)
print("=====================")
print(new_array.flatten(order = "F")) # F -> col (by deafult execute thorugh order format)

[1 2 3 3 4 5 6 7 8]
[1 3 6 2 4 7 3 5 8]


In [173]:
# convert single dim.. to multidimensional 
converting = np.array([1,2,3,4,5,6,7], ndmin =2)
print(converting)

[[1 2 3 4 5 6 7]]


In [177]:
# range() -> arange()
# startIndex , EndIndex , StepValue
# there is only one difference in range function we cant use float . arange we can use float number.

t = np.arange(10)
print(t)

[0 1 2 3 4 5 6 7 8 9]
