In [11]:
import numpy as np

arr = np.array([11,100,300,500,30,500])
print(arr)
print()
print(f" ndim : {arr.ndim}")
print()
print(f" shape : {arr.shape}")
print()
print(f" size : {arr.size}")
print()
print(f" dtype : {arr.dtype}")
print()
print(f" nbytes : {arr.nbytes}")

[ 11 100 300 500  30 500]

 ndim : 1

 shape : (6,)

 size : 6

 dtype : int32

 nbytes : 24


In [47]:
dim2 = np.array([[10,20,30,40,] , [50,60,70,80]])
print(dim2)

[[10 20 30 40]
 [50 60 70 80]]


In [49]:
print(dim2.ndim)

2


In [79]:
# reshape()
print(dim2.reshape(4,2))
print()
print(dim2.reshape(-1))

[[10 20]
 [30 40]
 [50 60]
 [70 80]]

[10 20 30 40 50 60 70 80]


In [53]:
# flatten
print(dim2.flatten())

[10 20 30 40 50 60 70 80]


In [55]:
print(dim2.flatten(order = "C"))

[10 20 30 40 50 60 70 80]


In [59]:
print(dim2.flatten(order = "F"))

[10 50 20 60 30 70 40 80]


In [61]:
# ravel()
ra = dim2.ravel()
print(ra)

[10 20 30 40 50 60 70 80]


In [71]:
ra = dim2.ravel(order = "C")
print(ra)

[10 20 30 40 50 60 70 80]


In [75]:
ra = dim2.ravel(order = "F")
print(ra)

[10 50 20 60 30 70 40 80]


In [81]:
# resize()
# negative dimension is not allowed in resize()
dim2.resize(2,4) # if you take a new varaible it will show None


In [85]:
print(dim2)

[[10 20 30 40]
 [50 60 70 80]]


In [87]:
# predefined arrays 

In [240]:
# random.rand(one-args)
q = np.random.rand(5)

In [242]:
q

array([0.25057308, 0.82800458, 0.97660802, 0.29728226, 0.22186812])

In [285]:
# random.randint(1,2) # two arguments
q1 = np.random.randint(1,100 , 10)
# q1 = np.random.randint() # error takes atleast one

In [289]:
q1

array([94, 86, 90, 55, 32, 14, 22,  1,  6, 90])

In [362]:
# within choice it will be giving the output
w = [12, 78, 900 , "abc" , 2+4j , 12 , 34]
e = np.random.choice(w)
print(e)

abc


In [364]:
e1 = np.random.choice(["python" , "sql"])
print(e1)

python


In [400]:
np.random.shuffle(w)

In [402]:
print(w)

[12, 900, 12, 34, 'abc', 78, (2+4j)]


In [449]:
# eye()
w = np.zeros(2)
w = np.zeros((2,2))
w = np.zeros((2,2,2) , dtype = "int")

In [451]:
w

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [447]:
w = np.ones(5)
w = np.ones((5,5))
w = np.ones((5,5,5), )

In [443]:
w

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [460]:
a = np.full((3,3),10)

In [464]:
a

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [478]:
# chage the dimnensions
q = np.eye(4)

In [480]:
q

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])